name: ezye
description: ezye Shopping app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  sms_autofill: ^2.3.0
  intl_phone_field: ^3.2.0
  flutter_slidable: ^3.0.0
  ticket_widget: ^0.0.1
  
  dotted_border: ^2.0.0+3
  flutter_rating_bar: ^4.0.1
  
  http: ^1.1.0
  cached_network_image: ^3.3.0
  
  flutter_svg: ^2.0.7
  im_stepper: ^1.0.1+1
  timeline_tile: ^2.0.0
  video_player: ^2.7.1
  firebase_auth: ^4.10.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  share_plus: ^6.0.1
  provider: ^6.0.5
  firebase_core: ^2.20.0
  searchfield: ^0.8.7
  dots_indicator: ^3.0.0
  easy_stepper: ^0.8.1
  animate_do: ^3.1.2
  phonepe_payment_sdk: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    
    - assets/png/
    - assets/svg/
    - assets/json/
    - assets/

  fonts:
   
    - family: Satoshi 
      fonts:
        - asset: fonts/Satoshi-Medium.ttf
          
          
   
